### PR TITLE
faq - Add navigation links to specific sections and questions

### PR DESCRIPTION
**Pull request by 2CATteam**
Hey there! I thought it might be useful to have a table of contents for the FAQ, since it's so long, so I thought I'd try and add one. The top now has links to each major section, and each major section contains links to each question. Thought this might make it easier to navigate the document

### CODE REVIEW

**Comment by Miepee** [comment]
ToC seems a good idea, but i'd make it display a bit differently. More akin to this:
image
So basically what your first attempt was going for. You can achieve a ToC like that by using "Spoiler brackets". 
```
<details>
<summary>header, can be a link too</summary>
have anything in here, even markdown
</details>
```
would produce this:
<details>
<summary>header, can be a link too</summary>
have anything in here, even markdown
</details>

I would've pushed a commit on your repo to implement this but doesn't seem I have write access there.

**Comment by 2CATteam** [comment]
Good suggestion, I didn't know that was an option! I'll implement that and update this PR

**Comment by 2CATteam** [comment]
Alright, that's implemented now. Something to note, though, is that the mobile view makes it pretty hard to expand each section, as the fact that the header is a link means that the only tap target is the little arrow. IDK how much the project needs to target mobile, but I thought I'd note that

**Comment by Miepee** [comment]
Can you put a table of contents text at the top?

**Comment by 2CATteam** [comment]
Yep, forgot to do that when I reverted to that original commit, haha

**Comment by Miepee** [comment]
Also just checked in on mobile, you can access it on the little arrow on the left, but you can also access it by typing the freespace on the right. So should be fine.

PR looks good to me now :+1:

**Comment by Lojemiru** [comment]
I'm on travel right now, but as soon as I'm on desktop again I'll check out the formatting and get this merged.

**Comment by Lojemiru** [comment]
Back! Merging now, thank you so much :)

**Comment by Lojemiru** [comment]
Hey, turns out our CSS theme interprets everything inside those hrefs as something other than markdown: 


I'd assume it's interpreting them as straight HTML, so that's probably a good direction to test first. Unfortunately I'm falling asleep at my desk so I won't be able to poke at it right now.

EDIT: First time I've reverted a PR. Seems like a new one will have to be made, as I can't reopen it :(

**Comment by 2CATteam** [comment]
That's fine, I'll fix it tomorrow myself and start a new one. If I can't fix it, I'll probably roll it back to the original layout, with a link to each section at the top, and a link to each question at the top of each section.

**Pull request merged**
